// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/parking_lot/parkinglot (interfaces: Service)

package mockservice

import (
	gomock "github.com/golang/mock/gomock"
	parkinglot "github.com/parking_lot/parkinglot"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockService) EXPECT() *MockServiceMockRecorder {
	return _m.recorder
}

// CreateParkingLot mocks base method
func (_m *MockService) CreateParkingLot(_param0 int64) error {
	ret := _m.ctrl.Call(_m, "CreateParkingLot", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateParkingLot indicates an expected call of CreateParkingLot
func (_mr *MockServiceMockRecorder) CreateParkingLot(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "CreateParkingLot", reflect.TypeOf((*MockService)(nil).CreateParkingLot), arg0)
}

// GetRegistrationNumbersByColor mocks base method
func (_m *MockService) GetRegistrationNumbersByColor(_param0 string) ([]string, error) {
	ret := _m.ctrl.Call(_m, "GetRegistrationNumbersByColor", _param0)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistrationNumbersByColor indicates an expected call of GetRegistrationNumbersByColor
func (_mr *MockServiceMockRecorder) GetRegistrationNumbersByColor(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetRegistrationNumbersByColor", reflect.TypeOf((*MockService)(nil).GetRegistrationNumbersByColor), arg0)
}

// GetSlotNumberByRegistrationNumber mocks base method
func (_m *MockService) GetSlotNumberByRegistrationNumber(_param0 string) (parkinglot.Slot, error) {
	ret := _m.ctrl.Call(_m, "GetSlotNumberByRegistrationNumber", _param0)
	ret0, _ := ret[0].(parkinglot.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlotNumberByRegistrationNumber indicates an expected call of GetSlotNumberByRegistrationNumber
func (_mr *MockServiceMockRecorder) GetSlotNumberByRegistrationNumber(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetSlotNumberByRegistrationNumber", reflect.TypeOf((*MockService)(nil).GetSlotNumberByRegistrationNumber), arg0)
}

// GetSlotNumbersByColor mocks base method
func (_m *MockService) GetSlotNumbersByColor(_param0 string) ([]parkinglot.Slot, error) {
	ret := _m.ctrl.Call(_m, "GetSlotNumbersByColor", _param0)
	ret0, _ := ret[0].([]parkinglot.Slot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlotNumbersByColor indicates an expected call of GetSlotNumbersByColor
func (_mr *MockServiceMockRecorder) GetSlotNumbersByColor(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetSlotNumbersByColor", reflect.TypeOf((*MockService)(nil).GetSlotNumbersByColor), arg0)
}

// GetStatus mocks base method
func (_m *MockService) GetStatus() ([]parkinglot.Parking, error) {
	ret := _m.ctrl.Call(_m, "GetStatus")
	ret0, _ := ret[0].([]parkinglot.Parking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus
func (_mr *MockServiceMockRecorder) GetStatus() *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetStatus", reflect.TypeOf((*MockService)(nil).GetStatus))
}

// Leave mocks base method
func (_m *MockService) Leave(_param0 int64) error {
	ret := _m.ctrl.Call(_m, "Leave", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Leave indicates an expected call of Leave
func (_mr *MockServiceMockRecorder) Leave(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Leave", reflect.TypeOf((*MockService)(nil).Leave), arg0)
}

// Park mocks base method
func (_m *MockService) Park(_param0 parkinglot.Car) (int64, error) {
	ret := _m.ctrl.Call(_m, "Park", _param0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Park indicates an expected call of Park
func (_mr *MockServiceMockRecorder) Park(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Park", reflect.TypeOf((*MockService)(nil).Park), arg0)
}
