// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/parking_lot/parkinglot (interfaces: Store)

// Package mockstore is a generated GoMock package.
package mockstore

import (
	gomock "github.com/golang/mock/gomock"
	parkinglot "github.com/parking_lot/parkinglot"
	reflect "reflect"
)

// MockStore is a mock of Store interface
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateSlots mocks base method
func (m *MockStore) CreateSlots(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSlots", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSlots indicates an expected call of CreateSlots
func (mr *MockStoreMockRecorder) CreateSlots(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSlots", reflect.TypeOf((*MockStore)(nil).CreateSlots), arg0)
}

// FillSlot mocks base method
func (m *MockStore) FillSlot(arg0 int, arg1 parkinglot.Car) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FillSlot", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// FillSlot indicates an expected call of FillSlot
func (mr *MockStoreMockRecorder) FillSlot(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FillSlot", reflect.TypeOf((*MockStore)(nil).FillSlot), arg0, arg1)
}

// FreeSlot mocks base method
func (m *MockStore) FreeSlot(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FreeSlot", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// FreeSlot indicates an expected call of FreeSlot
func (mr *MockStoreMockRecorder) FreeSlot(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FreeSlot", reflect.TypeOf((*MockStore)(nil).FreeSlot), arg0)
}

// GetAvailableSlot mocks base method
func (m *MockStore) GetAvailableSlot() (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableSlot")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableSlot indicates an expected call of GetAvailableSlot
func (mr *MockStoreMockRecorder) GetAvailableSlot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableSlot", reflect.TypeOf((*MockStore)(nil).GetAvailableSlot))
}

// GetCars mocks base method
func (m *MockStore) GetCars(arg0 parkinglot.FilterType, arg1 interface{}) ([]parkinglot.Car, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCars", arg0, arg1)
	ret0, _ := ret[0].([]parkinglot.Car)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCars indicates an expected call of GetCars
func (mr *MockStoreMockRecorder) GetCars(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCars", reflect.TypeOf((*MockStore)(nil).GetCars), arg0, arg1)
}

// GetSlotNumbers mocks base method
func (m *MockStore) GetSlotNumbers(arg0 parkinglot.FilterType, arg1 interface{}) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlotNumbers", arg0, arg1)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlotNumbers indicates an expected call of GetSlotNumbers
func (mr *MockStoreMockRecorder) GetSlotNumbers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlotNumbers", reflect.TypeOf((*MockStore)(nil).GetSlotNumbers), arg0, arg1)
}

// GetStatus mocks base method
func (m *MockStore) GetStatus() ([]parkinglot.Parking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].([]parkinglot.Parking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus
func (mr *MockStoreMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockStore)(nil).GetStatus))
}
